version: '2'

volumes:
  nfsdnsmasq:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.0.0.100,rw,nfsvers=4,async
      device: ":/mnt/barracuda/nfsdnsmasq"

services:
  dnsmasq:
    image: jpillora/dnsmasq
    container_name: dnsmasq
    restart: unless-stopped
    ports:
      - 53:53
      - 5380:8080
    volumes:
      - nfsdnsmasq:/etc
    logging:
      options:
        max-size: '100m'
